# Taps
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"

# Binaries
brew "python"
brew "awscli"
brew "coreutils"
brew "adr-tools"
# brew "macvim --with-cscope --with-lua --override-system-vim"
brew "go"

# Apps
cask "iterm2"
cask "atom"
cask "google-chrome"
cask "google-backup-and-sync"
cask "slack"
cask "macdown"
cask "java"
cask "intellij-idea-ce"
cask "visual-studio-code"
cask "macvim"
