# Enable extended globbing
setopt extended_glob

# Load the shell dotfiles
# (~/.extra) can be used for other settings you don't want to commit.
for dot_file in ~/.{exports,aliases,functions,extra}; do
	source "${dot_file}"
done

# Shortcuts
bindkey "^[^[[D" backward-word
bindkey "^[^[[C" forward-word
bindkey \^U backward-kill-line
bindkey '\e_' insert-last-word
